from __future__ import annotations

from dataclasses import asdict, dataclass
try:
    from enum import StrEnum
except ImportError:  # pragma: no cover - exercised by the Python 3.10 CI job
    from enum import Enum

    class StrEnum(str, Enum):
        """Python 3.10 compatibility for enum.StrEnum's string behavior."""

        def __str__(self) -> str:
            return str(self.value)
from typing import Any


class ErrorCode(StrEnum):
    INVALID_JSON = "INVALID_JSON"
    UNKNOWN_DOCUMENT_TYPE = "UNKNOWN_DOCUMENT_TYPE"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    DUPLICATE_ID = "DUPLICATE_ID"
    DANGLING_REFERENCE = "DANGLING_REFERENCE"
    PRODUCER_MISMATCH = "PRODUCER_MISMATCH"
    INVALID_ESTIMATE_RANGE = "INVALID_ESTIMATE_RANGE"
    UNKNOWN_VALUE_REQUIRED = "UNKNOWN_VALUE_REQUIRED"
    FORMULA_REQUIRED = "FORMULA_REQUIRED"
    PARSE_FAILURE_CANNOT_PRODUCE_VALID_ZERO = "PARSE_FAILURE_CANNOT_PRODUCE_VALID_ZERO"
    VERIFIED_REQUIRES_VERIFIED_OUTCOME_DOCUMENT = "VERIFIED_REQUIRES_VERIFIED_OUTCOME_DOCUMENT"
    NON_ADDITIVE_METRIC_INCLUDED_IN_TOTAL = "NON_ADDITIVE_METRIC_INCLUDED_IN_TOTAL"
    UNATTRIBUTED_COST_IS_NOT_SAVINGS = "UNATTRIBUTED_COST_IS_NOT_SAVINGS"
    MUTATING_COMMAND_NOT_ALLOWED = "MUTATING_COMMAND_NOT_ALLOWED"
    MISSING_ACTIVITY_MUST_BE_UNKNOWN = "MISSING_ACTIVITY_MUST_BE_UNKNOWN"
    UNSUPPORTED_PRICE_MUST_BE_UNKNOWN = "UNSUPPORTED_PRICE_MUST_BE_UNKNOWN"
    EXCLUSIVE_OVERLAP_INCLUDED_MORE_THAN_ONCE = "EXCLUSIVE_OVERLAP_INCLUDED_MORE_THAN_ONCE"
    AGGREGATE_DOES_NOT_RECONCILE = "AGGREGATE_DOES_NOT_RECONCILE"
    REPORT_DISPLAY_REFERENCE_MISSING = "REPORT_DISPLAY_REFERENCE_MISSING"
    COMPLETE_REPORT_MISSING_PRODUCER = "COMPLETE_REPORT_MISSING_PRODUCER"
    ILLUSTRATIVE_DISCLOSURE_REQUIRED = "ILLUSTRATIVE_DISCLOSURE_REQUIRED"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    MANIFEST_MISSING = "MANIFEST_MISSING"
    ARTIFACT_MISSING = "ARTIFACT_MISSING"
    ARTIFACT_HASH_MISMATCH = "ARTIFACT_HASH_MISMATCH"
    RUN_ID_MISMATCH = "RUN_ID_MISMATCH"
    MODE_MISMATCH = "MODE_MISMATCH"


@dataclass(frozen=True, slots=True)
class ValidationIssue:
    code: ErrorCode
    message: str
    path: str = "$"
    detail: Any | None = None

    def as_dict(self) -> dict[str, Any]:
        result = asdict(self)
        result["code"] = self.code.value
        if result["detail"] is None:
            result.pop("detail")
        return result
